### ISSUE TITLE
how to use this project.

### ISSUE THREAD

**Issue by amit13091992** [papan01/Live555-server-android#1]
@papan01 
will u please describe the process, that how can i use this project. i am not able to understand, kindly please give a guidance for this project

**Comment by papan01** [comment]
@amit13091992 
This project is used the live555 rtsp server on android. When you run the app and click the button,the server will be enable. At /jni/live555test2.cpp, you can set your streaming path. In my program:

```
char const* streamName = "h264test";
char const* inputFileName = "/sdcard/test.264";
```
I have a test.264 file in my android phone, so i can play test.264 through VLC, using URL: rtsp://xxx.xxx.xxx.xxx:port/h264test. I tested it in the same network segment.

Sorry, my English is poor,i hope it would help to you.

**Comment by amit13091992** [comment]
Plz would you tell me how can i give path for the file in android phone,
and where to place that file.

**Comment by papan01** [comment]
You can put the file anywhere. If the file is in the SD card, the path should be as "/sdcard/<your name of file>".
If the file in the movies folder, the path will be "/sdcard/movies/<your name of file>" 
Your name of file must add file suffix.

**Comment by amit13091992** [comment]
Thanku for your guide, i will try it, and if i will get any doubt i will
reach to u😁😊
